### ISSUE TITLE
Problème "Retour" dans le TAJ

### ISSUE THREAD

**Issue by Wiggsi** [AlbeBertin/SiteALF#12]
Lorsque l'on sélectionne un individu et que l'on clic sur "Retour", le retour se fait sur le TAJ mais si je clic sur modifier, que je fais "Retour à la fiche", c'est ok je retourne sur la fiche mais si je clic sur "Retour", je retourne dans "Modifier". (Faire en sorte que ça renvoi vers le TAJ)

**Comment by AlbeBertin** [comment]
#17

**Comment by AlbeBertin** [comment]
Ou si retour en arrière donne sur modification, retourner 2 fois en arrière
Ou modifier le retour  des modifications pour un retour en arrière js
