### ISSUE TITLE
Création d'un système de Log

### ISSUE THREAD

**Issue by Wiggsi** [AlbeBertin/SiteALF#55]
L'on m'a soumis le souhait d'avoir un système de log afin de savoir tout les ajouts, toute les modifications de fichier effectuée (Par qui et Quand). Le tout serait en accès uniquement pour les Cmt, LCL,Col et admin.
Possible ?

**Comment by AlbeBertin** [comment]
Système basique créé. À voir si améliorations nécessaires.
